# Site settings
title: "Nick Wilfahrt Resume"
description: "Nick Wilfahrt's resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Nick Wilfahrt"
resume_title:                   "Information Security Professional"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "nicholas.wilfahrt@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(612) 704-8616"
resume_contact_address:         "10101 Bren Rd E, 309, Minnetonka, MN 55343"

resume_header_contact_info:     "10101 Bren Rd E, 309, Minnetonka, MN 55343 • (612) 704-8616 • nicholas.wilfahrt@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am an Information and Application Security professional with experience in both agile, SOA driven environments, more traditional settings and businesses in between. I have skill with a wide range of technologies and products along with experience taking large initiatives, breaking them down into projects and finishing the work that is required to complete them. I have experience supporting SOCI and II audits as well as other kinds of policy and governance problems. My tech interests include automation, problem solving and my homelab</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Electronickss"
  resume_twitter_url:           "http://twitter.com/ElectroNickss"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/nickwilfahrt/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://nickwilfahrt.com"
  # resume_medium_url:            "https://medium.com/@"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
